### ISSUE TITLE
使用v100推理遇到错误

### ISSUE THREAD

**Issue by zhang992253635** [THUDM/GLM-130B#153]
> Model initialized in 1086.2s
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/xh/code/GLM/glm-trainning/generate.py", line 219, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/xh/code/GLM/glm-trainning/generate.py", line 219, in <module>
  File "/home/xh/code/GLM/glm-trainning/generate.py", line 219, in <module>
  File "/home/xh/code/GLM/glm-trainning/generate.py", line 219, in <module>
  File "/home/xh/code/GLM/glm-trainning/generate.py", line 219, in <module>
  File "/home/xh/code/GLM/glm-trainning/generate.py", line 219, in <module>
  File "/home/xh/code/GLM/glm-trainning/generate.py", line 219, in <module>
  File "/home/xh/code/GLM/glm-trainning/generate.py", line 219, in <module>
    main(args)
  File "/home/xh/code/GLM/glm-trainning/generate.py", line 212, in main
    main(args)
  File "/home/xh/code/GLM/glm-trainning/generate.py", line 212, in main
    main(args)
  File "/home/xh/code/GLM/glm-trainning/generate.py", line 212, in main
        main(args)main(args)

    main(args)  File "/home/xh/code/GLM/glm-trainning/generate.py", line 212, in main
  File "/home/xh/code/GLM/glm-trainning/generate.py", line 212, in main
    main(args)
main(args)

  File "/home/xh/code/GLM/glm-trainning/generate.py", line 212, in main
  File "/home/xh/code/GLM/glm-trainning/generate.py", line 212, in main
      File "/home/xh/code/GLM/glm-trainning/generate.py", line 212, in main
generate_continually(process, args.input_source)
      File "/opt/conda/lib/python3.8/site-packages/SwissArmyTransformer/generation/utils.py", line 72, in generate_continually
generate_continually(process, args.input_source)
  File "/opt/conda/lib/python3.8/site-packages/SwissArmyTransformer/generation/utils.py", line 72, in generate_continually
    generate_continually(process, args.input_source)
  File "/opt/conda/lib/python3.8/site-packages/SwissArmyTransformer/generation/utils.py", line 72, in generate_continually
    generate_continually(process, args.input_source)
generate_continually(process, args.input_source)
  File "/opt/conda/lib/python3.8/site-packages/SwissArmyTransformer/generation/utils.py", line 72, in generate_continually
  File "/opt/conda/lib/python3.8/site-packages/SwissArmyTransformer/generation/utils.py", line 72, in generate_continually
        generate_continually(process, args.input_source)generate_continually(process, args.input_source)

      File "/opt/conda/lib/python3.8/site-packages/SwissArmyTransformer/generation/utils.py", line 72, in generate_continually
  File "/opt/conda/lib/python3.8/site-packages/SwissArmyTransformer/generation/utils.py", line 72, in generate_continually
generate_continually(process, args.input_source)
  File "/opt/conda/lib/python3.8/site-packages/SwissArmyTransformer/generation/utils.py", line 72, in generate_continually
    inputs = fin.readlines()
          File "/opt/conda/lib/python3.8/encodings/ascii.py", line 26, in decode
    inputs = fin.readlines()
    inputs = fin.readlines()inputs = fin.readlines()inputs = fin.readlines()

inputs = fin.readlines()
  File "/opt/conda/lib/python3.8/encodings/ascii.py", line 26, in decode
  File "/opt/conda/lib/python3.8/encodings/ascii.py", line 26, in decode
inputs = fin.readlines()inputs = fin.readlines()
  File "/opt/conda/lib/python3.8/encodings/ascii.py", line 26, in decode

  File "/opt/conda/lib/python3.8/encodings/ascii.py", line 26, in decode
  File "/opt/conda/lib/python3.8/encodings/ascii.py", line 26, in decode
  File "/opt/conda/lib/python3.8/encodings/ascii.py", line 26, in decode
  File "/opt/conda/lib/python3.8/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
return codecs.ascii_decode(input, self.errors)[0]return codecs.ascii_decode(input, self.errors)[0]

    return codecs.ascii_decode(input, self.errors)[0]UnicodeDecodeError    return codecs.ascii_decode(input, self.errors)[0]    return codecs.ascii_decode(input, self.errors)[0]UnicodeDecodeError

return codecs.ascii_decode(input, self.errors)[0]
: UnicodeDecodeErrorreturn codecs.ascii_decode(input, self.errors)[0]
: 'ascii' codec can't decode byte 0xe8 in position 0: ordinal not in range(128)'ascii' codec can't decode byte 0xe8 in position 0: ordinal not in range(128)UnicodeDecodeError
:

: UnicodeDecodeError'ascii' codec can't decode byte 0xe8 in position 0: ordinal not in range(128)UnicodeDecodeErrorUnicodeDecodeError
: 'ascii' codec can't decode byte 0xe8 in position 0: ordinal not in range(128)'ascii' codec can't decode byte 0xe8 in position 0: ordinal not in range(128)
UnicodeDecodeError: : 'ascii' codec can't decode byte 0xe8 in position 0: ordinal not in range(128)'ascii' codec can't decode byte 0xe8 in position 0: ordinal not in range(128)

:
'ascii' codec can't decode byte 0xe8 in position 0: ordinal not in range(128)

**Comment by QYY1028** [comment]
https://github.com/THUDM/SwissArmyTransformer/pull/84/commits/3670577c272fb019a24370b2907fa933465755ce
