### ISSUE TITLE
[ERROR] `bash scripts/generate.sh --input-source interactive` 报错

### ISSUE THREAD

**Issue by SniperM99** [THUDM/GLM-130B#177]
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[2023-06-13 16:50:42,866] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-06-13 16:50:42,966] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-06-13 16:50:43,183] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-06-13 16:50:43,194] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-06-13 16:50:43,276] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-06-13 16:50:43,301] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-06-13 16:50:43,331] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-06-13 16:50:43,426] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/home/xxz/GLM-130B-main/generate.py", line 9, in <module>
    from SwissArmyTransformer import mpu
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/__init__.py", line 2, in <module>
    from .training.deepspeed_training import training_main
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/training/__init__.py", line 1, in <module>
    from .deepspeed_training import initialize_distributed, set_random_seed
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/training/deepspeed_training.py", line 40, in <module>
    from SwissArmyTransformer.ops import LayerNorm
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/ops/__init__.py", line 15, in <module>
    from .layernorm import LayerNorm
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/ops/layernorm.py", line 2, in <module>
    from apex.normalization.fused_layer_norm import FusedLayerNorm
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/apex/__init__.py", line 13, in <module>
    from pyramid.session import UnencryptedCookieSessionFactoryConfig
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)
Traceback (most recent call last):
  File "/home/xxz/GLM-130B-main/generate.py", line 9, in <module>
    from SwissArmyTransformer import mpu
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/__init__.py", line 2, in <module>
    from .training.deepspeed_training import training_main
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/training/__init__.py", line 1, in <module>
    from .deepspeed_training import initialize_distributed, set_random_seed
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/training/deepspeed_training.py", line 40, in <module>
    from SwissArmyTransformer.ops import LayerNorm
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/ops/__init__.py", line 15, in <module>
    from .layernorm import LayerNorm
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/ops/layernorm.py", line 2, in <module>
    from apex.normalization.fused_layer_norm import FusedLayerNorm
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/apex/__init__.py", line 13, in <module>
    from pyramid.session import UnencryptedCookieSessionFactoryConfig
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)
Traceback (most recent call last):
  File "/home/xxz/GLM-130B-main/generate.py", line 9, in <module>
    from SwissArmyTransformer import mpu
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/__init__.py", line 2, in <module>
    from .training.deepspeed_training import training_main
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/training/__init__.py", line 1, in <module>
    from .deepspeed_training import initialize_distributed, set_random_seed
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/training/deepspeed_training.py", line 40, in <module>
    from SwissArmyTransformer.ops import LayerNorm
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/ops/__init__.py", line 15, in <module>
    from .layernorm import LayerNorm
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/ops/layernorm.py", line 2, in <module>
    from apex.normalization.fused_layer_norm import FusedLayerNorm
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/apex/__init__.py", line 13, in <module>
    from pyramid.session import UnencryptedCookieSessionFactoryConfig
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)
Traceback (most recent call last):
  File "/home/xxz/GLM-130B-main/generate.py", line 9, in <module>
    from SwissArmyTransformer import mpu
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/__init__.py", line 2, in <module>
    from .training.deepspeed_training import training_main
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/training/__init__.py", line 1, in <module>
    from .deepspeed_training import initialize_distributed, set_random_seed
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/training/deepspeed_training.py", line 40, in <module>
    from SwissArmyTransformer.ops import LayerNorm
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/ops/__init__.py", line 15, in <module>
    from .layernorm import LayerNorm
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/ops/layernorm.py", line 2, in <module>
    from apex.normalization.fused_layer_norm import FusedLayerNorm
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/apex/__init__.py", line 13, in <module>
    from pyramid.session import UnencryptedCookieSessionFactoryConfig
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)
Traceback (most recent call last):
  File "/home/xxz/GLM-130B-main/generate.py", line 9, in <module>
    from SwissArmyTransformer import mpu
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/__init__.py", line 2, in <module>
    from .training.deepspeed_training import training_main
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/training/__init__.py", line 1, in <module>
    from .deepspeed_training import initialize_distributed, set_random_seed
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/training/deepspeed_training.py", line 40, in <module>
    from SwissArmyTransformer.ops import LayerNorm
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/ops/__init__.py", line 15, in <module>
    from .layernorm import LayerNorm
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/ops/layernorm.py", line 2, in <module>
    from apex.normalization.fused_layer_norm import FusedLayerNorm
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/apex/__init__.py", line 13, in <module>
    from pyramid.session import UnencryptedCookieSessionFactoryConfig
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)
Traceback (most recent call last):
  File "/home/xxz/GLM-130B-main/generate.py", line 9, in <module>
    from SwissArmyTransformer import mpu
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/__init__.py", line 2, in <module>
    from .training.deepspeed_training import training_main
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/training/__init__.py", line 1, in <module>
    from .deepspeed_training import initialize_distributed, set_random_seed
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/training/deepspeed_training.py", line 40, in <module>
    from SwissArmyTransformer.ops import LayerNorm
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/ops/__init__.py", line 15, in <module>
    from .layernorm import LayerNorm
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/ops/layernorm.py", line 2, in <module>
    from apex.normalization.fused_layer_norm import FusedLayerNorm
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/apex/__init__.py", line 13, in <module>
    from pyramid.session import UnencryptedCookieSessionFactoryConfig
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)
Traceback (most recent call last):
  File "/home/xxz/GLM-130B-main/generate.py", line 9, in <module>
    from SwissArmyTransformer import mpu
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/__init__.py", line 2, in <module>
    from .training.deepspeed_training import training_main
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/training/__init__.py", line 1, in <module>
    from .deepspeed_training import initialize_distributed, set_random_seed
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/training/deepspeed_training.py", line 40, in <module>
    from SwissArmyTransformer.ops import LayerNorm
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/ops/__init__.py", line 15, in <module>
    from .layernorm import LayerNorm
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/ops/layernorm.py", line 2, in <module>
    from apex.normalization.fused_layer_norm import FusedLayerNorm
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/apex/__init__.py", line 13, in <module>
    from pyramid.session import UnencryptedCookieSessionFactoryConfig
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)
Traceback (most recent call last):
  File "/home/xxz/GLM-130B-main/generate.py", line 9, in <module>
    from SwissArmyTransformer import mpu
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/__init__.py", line 2, in <module>
    from .training.deepspeed_training import training_main
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/training/__init__.py", line 1, in <module>
    from .deepspeed_training import initialize_distributed, set_random_seed
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/training/deepspeed_training.py", line 40, in <module>
    from SwissArmyTransformer.ops import LayerNorm
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/ops/__init__.py", line 15, in <module>
    from .layernorm import LayerNorm
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/SwissArmyTransformer/ops/layernorm.py", line 2, in <module>
    from apex.normalization.fused_layer_norm import FusedLayerNorm
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/apex/__init__.py", line 13, in <module>
    from pyramid.session import UnencryptedCookieSessionFactoryConfig
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 29739) of binary: /home/xxz/workspace/python_env/glm-130b/bin/python
Traceback (most recent call last):
  File "/home/xxz/workspace/python_env/glm-130b/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/xxz/workspace/python_env/glm-130b/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by SniperM99** [comment]
请问，大家有遇到过类似问题吗？

**Comment by SniperM99** [comment]
我的python版本是3.10，所以不支持2.10版本的numpy
参考 ![numpy](https://img-blog.csdnimg.cn/c570a76d62054432a103454c559800c8.png)

**Comment by Stardust-minus** [comment]
遇到了同样的问题，有解决办法吗

**Comment by SniperM99** [comment]
> 遇到了同样的问题，有解决办法吗

没有啊，似乎是torch版本太高导致的

**Comment by yandan1234** [comment]
应该是apex 安装错误，按照这个来https://github.com/NVIDIA/apex/#linux

**Comment by weichen12345** [comment]
同样问题，要疯了

**Comment by qh010207** [comment]
apex 问题，nvidia官网下载
