### ISSUE TITLE
bash scripts/generate.sh --input-source interactive运行报错

### ISSUE THREAD

**Issue by wudajun7509** [THUDM/GLM-130B#184]
No module named 'fused_layer_norm_cuda'，apex已经安装完成的，环境是torch 2.01+cu11.8，硬件3090*8 INT4量化

**Comment by wudajun7509** [comment]
我将torch降到了1.13+cu11.7，同样报错，其中torch、apex import都正常

**Comment by wudajun7509** [comment]
[2023-06-18 07:18:33,540] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
WARNING: No training data specified
WARNING: No training data specified
WARNING: No training data specified
WARNING: No training data specified
WARNING: No training data specified
WARNING: No training data specified
WARNING: No training data specified
WARNING: No training data specified
using world size: 8 and model-parallel size: 8
> padded vocab (size: 150528) with 0 dummy tokens (new size: 150528)
> initializing model parallel with size 8
> Set tokenizer as a icetk-glm-130B tokenizer! Now you can get_tokenizer() everywhere.
Traceback (most recent call last):
  File "/home/ai/glm-130b/generate.py", line 215, in <module>
    main(args)
  File "/home/ai/glm-130b/generate.py", line 160, in main
    model, tokenizer = initialize_model_and_tokenizer(args)
  File "/home/ai/glm-130b/initialize.py", line 64, in initialize_model_and_tokenizer
Traceback (most recent call last):
  File "/home/ai/glm-130b/generate.py", line 215, in <module>
    model = GLM130B(args).half()
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/official/glm130B_model.py", line 327, in __init__
    main(args)
  File "/home/ai/glm-130b/generate.py", line 160, in main
    super().__init__(
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/base_model.py", line 63, in __init__
    model, tokenizer = initialize_model_and_tokenizer(args)
  File "/home/ai/glm-130b/initialize.py", line 64, in initialize_model_and_tokenizer
    model = GLM130B(args).half()
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/official/glm130B_model.py", line 327, in __init__
    self.transformer = BaseTransformer(
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 417, in __init__
    super().__init__(
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/base_model.py", line 63, in __init__
    self.transformer = BaseTransformer(
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 417, in __init__
        [get_layer(layer_id) for layer_id in range(num_layers)])[get_layer(layer_id) for layer_id in range(num_layers)])

  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 417, in <listcomp>
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 417, in <listcomp>
    [get_layer(layer_id) for layer_id in range(num_layers)])
    [get_layer(layer_id) for layer_id in range(num_layers)])  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 393, in get_layer

  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 393, in get_layer
    return BaseTransformerLayer(
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 268, in __init__
    return BaseTransformerLayer(
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 268, in __init__
    self.input_layernorm = layernorm(hidden_size, eps=layernorm_epsilon)
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/ops/layernorm.py", line 5, in __init__
    self.input_layernorm = layernorm(hidden_size, eps=layernorm_epsilon)
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/ops/layernorm.py", line 5, in __init__
        super().__init__(*args, **kwargs)super().__init__(*args, **kwargs)

  File "/home/ai/.local/lib/python3.10/site-packages/apex/normalization/fused_layer_norm.py", line 268, in __init__
  File "/home/ai/.local/lib/python3.10/site-packages/apex/normalization/fused_layer_norm.py", line 268, in __init__
    fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fused_layer_norm_cuda'
ModuleNotFoundError: No module named 'fused_layer_norm_cuda'
Traceback (most recent call last):
  File "/home/ai/glm-130b/generate.py", line 215, in <module>
Traceback (most recent call last):
  File "/home/ai/glm-130b/generate.py", line 215, in <module>
    main(args)
  File "/home/ai/glm-130b/generate.py", line 160, in main
        main(args)model, tokenizer = initialize_model_and_tokenizer(args)

  File "/home/ai/glm-130b/generate.py", line 160, in main
  File "/home/ai/glm-130b/initialize.py", line 64, in initialize_model_and_tokenizer
    model = GLM130B(args).half()
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/official/glm130B_model.py", line 327, in __init__
    model, tokenizer = initialize_model_and_tokenizer(args)
  File "/home/ai/glm-130b/initialize.py", line 64, in initialize_model_and_tokenizer
    model = GLM130B(args).half()
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/official/glm130B_model.py", line 327, in __init__
    super().__init__(
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/base_model.py", line 63, in __init__
    self.transformer = BaseTransformer(
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 417, in __init__
    super().__init__(
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/base_model.py", line 63, in __init__
    self.transformer = BaseTransformer(
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 417, in __init__
    [get_layer(layer_id) for layer_id in range(num_layers)])
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 417, in <listcomp>
    [get_layer(layer_id) for layer_id in range(num_layers)])
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 417, in <listcomp>
    [get_layer(layer_id) for layer_id in range(num_layers)])
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 393, in get_layer
        [get_layer(layer_id) for layer_id in range(num_layers)])return BaseTransformerLayer(

  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 393, in get_layer
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 268, in __init__
    self.input_layernorm = layernorm(hidden_size, eps=layernorm_epsilon)
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/ops/layernorm.py", line 5, in __init__
    return BaseTransformerLayer(
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 268, in __init__
    super().__init__(*args, **kwargs)
  File "/home/ai/.local/lib/python3.10/site-packages/apex/normalization/fused_layer_norm.py", line 268, in __init__
    self.input_layernorm = layernorm(hidden_size, eps=layernorm_epsilon)
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/ops/layernorm.py", line 5, in __init__
    fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    super().__init__(*args, **kwargs)
  File "/home/ai/.local/lib/python3.10/site-packages/apex/normalization/fused_layer_norm.py", line 268, in __init__
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
    fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
ModuleNotFoundError: No module named 'fused_layer_norm_cuda'
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fused_layer_norm_cuda'
Traceback (most recent call last):
  File "/home/ai/glm-130b/generate.py", line 215, in <module>
    main(args)
  File "/home/ai/glm-130b/generate.py", line 160, in main
    model, tokenizer = initialize_model_and_tokenizer(args)
  File "/home/ai/glm-130b/initialize.py", line 64, in initialize_model_and_tokenizer
    model = GLM130B(args).half()
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/official/glm130B_model.py", line 327, in __init__
    Traceback (most recent call last):
super().__init__(
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/base_model.py", line 63, in __init__
  File "/home/ai/glm-130b/generate.py", line 215, in <module>
Traceback (most recent call last):
  File "/home/ai/glm-130b/generate.py", line 215, in <module>
    self.transformer = BaseTransformer(
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 417, in __init__
        [get_layer(layer_id) for layer_id in range(num_layers)])main(args)

main(args)  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 417, in <listcomp>

  File "/home/ai/glm-130b/generate.py", line 160, in main
  File "/home/ai/glm-130b/generate.py", line 160, in main
        model, tokenizer = initialize_model_and_tokenizer(args)model, tokenizer = initialize_model_and_tokenizer(args)

  File "/home/ai/glm-130b/initialize.py", line 64, in initialize_model_and_tokenizer
  File "/home/ai/glm-130b/initialize.py", line 64, in initialize_model_and_tokenizer
    [get_layer(layer_id) for layer_id in range(num_layers)])
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 393, in get_layer
    model = GLM130B(args).half()
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/official/glm130B_model.py", line 327, in __init__
    model = GLM130B(args).half()
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/official/glm130B_model.py", line 327, in __init__
    return BaseTransformerLayer(
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 268, in __init__
    super().__init__(
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/base_model.py", line 63, in __init__
    super().__init__(
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/base_model.py", line 63, in __init__
    self.transformer = BaseTransformer(
      File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 417, in __init__
self.input_layernorm = layernorm(hidden_size, eps=layernorm_epsilon)
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/ops/layernorm.py", line 5, in __init__
    Traceback (most recent call last):
self.transformer = BaseTransformer(
  File "/home/ai/glm-130b/generate.py", line 215, in <module>
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 417, in __init__
    super().__init__(*args, **kwargs)
  File "/home/ai/.local/lib/python3.10/site-packages/apex/normalization/fused_layer_norm.py", line 268, in __init__
    [get_layer(layer_id) for layer_id in range(num_layers)])
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 417, in <listcomp>
    fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    [get_layer(layer_id) for layer_id in range(num_layers)])
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 417, in <listcomp>
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
    main(args)
      File "/home/ai/glm-130b/generate.py", line 160, in main
[get_layer(layer_id) for layer_id in range(num_layers)])
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 393, in get_layer
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        [get_layer(layer_id) for layer_id in range(num_layers)])model, tokenizer = initialize_model_and_tokenizer(args)

  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 393, in get_layer
  File "/home/ai/glm-130b/initialize.py", line 64, in initialize_model_and_tokenizer
    return BaseTransformerLayer(
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 268, in __init__
ModuleNotFoundError    : model = GLM130B(args).half()No module named 'fused_layer_norm_cuda'

  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/official/glm130B_model.py", line 327, in __init__
        self.input_layernorm = layernorm(hidden_size, eps=layernorm_epsilon)return BaseTransformerLayer(

  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/ops/layernorm.py", line 5, in __init__
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 268, in __init__
    super().__init__(
      File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/base_model.py", line 63, in __init__
super().__init__(*args, **kwargs)
  File "/home/ai/.local/lib/python3.10/site-packages/apex/normalization/fused_layer_norm.py", line 268, in __init__
        self.transformer = BaseTransformer(self.input_layernorm = layernorm(hidden_size, eps=layernorm_epsilon)

  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 417, in __init__
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/ops/layernorm.py", line 5, in __init__
    fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
      File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
super().__init__(*args, **kwargs)
  File "/home/ai/.local/lib/python3.10/site-packages/apex/normalization/fused_layer_norm.py", line 268, in __init__
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
    [get_layer(layer_id) for layer_id in range(num_layers)])
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 417, in <listcomp>
    fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
    [get_layer(layer_id) for layer_id in range(num_layers)])
ModuleNotFoundError  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 393, in get_layer
: No module named 'fused_layer_norm_cuda'
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
    return BaseTransformerLayer(
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/model/transformer.py", line 268, in __init__
ModuleNotFoundError: No module named 'fused_layer_norm_cuda'
    self.input_layernorm = layernorm(hidden_size, eps=layernorm_epsilon)
  File "/home/ai/.local/lib/python3.10/site-packages/SwissArmyTransformer/ops/layernorm.py", line 5, in __init__
    super().__init__(*args, **kwargs)
  File "/home/ai/.local/lib/python3.10/site-packages/apex/normalization/fused_layer_norm.py", line 268, in __init__
    fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fused_layer_norm_cuda'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2186) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/home/ai/.local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/ai/.local/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/ai/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/ai/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/ai/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ai/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/home/ai/glm-130b/generate.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-06-18_07:18:42
  host      : ai
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2187)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-06-18_07:18:42
  host      : ai
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 2188)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by wudajun7509** [comment]
已解决，apex编译问题

**Comment by ZSitong** [comment]
请问是如何解决的？
