### ISSUE TITLE
Met exception when run the fastertransformers demo

### ISSUE THREAD

**Issue by hmzo** [THUDM/GLM-130B#41]
Thank you for your awesome work!
when I follow the steps provided [here](https://github.com/THUDM/GLM-130B/blob/main/docs/inference-with-fastertransformer.md), I just met the exception:
```
Traceback (most recent call last):
  File "/FasterTransformer/examples/pytorch/glm/glm_server.py", line 101, in <module>
    if not glm.load(ckpt_path=args.ckpt_path):
  File "/FasterTransformer/examples/pytorch/glm/../../../examples/pytorch/glm/utils/glm.py", line 319, in load
    is_load = self.weights.load(ckpt_path, tensor_para_rank=self.tensor_para_rank,
  File "/FasterTransformer/examples/pytorch/glm/../../../examples/pytorch/glm/utils/glm.py", line 190, in load
    scale.extend([module[f'transformer.layers.{i}.attention.query_key_value.weight_scale'].reshape(head_num, num_splits, size_per_head).permute(1, 0, 2).reshape(3, local_dim) for i in range(layer_num)])
  File "/FasterTransformer/examples/pytorch/glm/../../../examples/pytorch/glm/utils/glm.py", line 190, in <listcomp>
    scale.extend([module[f'transformer.layers.{i}.attention.query_key_value.weight_scale'].reshape(head_num, num_splits, size_per_head).permute(1, 0, 2).reshape(3, local_dim) for i in range(layer_num)])
KeyError: 'transformer.layers.0.attention.query_key_value.weight_scale'
```
It seems that state_dict is missing some keys

**Comment by prnake** [comment]
It is probably because the download ckpt is in fp16. To run in int4 or int8 mode, please run [convert_tp.py](https://github.com/THUDM/GLM-130B/blob/main/tools/convert_tp.py) to generate the quantmized ckpt.
